### ISSUE TITLE
Animate Text Layer

### ISSUE THREAD

**Issue by theposch** [k-vyn/framer-ios-kit#17]
Is it possible to change the text of a Text Layer?
Example:

```
text = new ios.Text
    text: 'Initiating...'
    font: 'Vaud'
    fontSize: 20
    textAlign: 'center'
    color: '#fff'
    fontWeight: 400
    constraints:
        leading: 16
        top: 350
        width: 320
    opacity: 0


text.states.add
    one: 
        text: "Communicating with server..."


    two:
        text: "Completing upload..."
```
